### ISSUE TITLE
FS: Sitter, Availability

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-pine-cone#45]
- From the profile page, a user can toggle an option to become a sitter.  Upon submitting the form, the user becomes a sitter. This will add the availability tab to the profile panel
- Availability: We have a [mockup](https://drive.google.com/drive/u/1/folders/1RwsokfJyUowMrnaMFMLJkg5iC7wLi39t) for that, but it needs to be tweaked. Maybe an easier alternative would be for the user to enter their available hours for each weekday, plus select a date or range of dates in the calendar when they are NOT willing to work. 
- Rate: We also need the user to enter they hourly rate. To keep things simple for now, it will be just a base rate. But later on we could more granularity, e.g (different rate for certain weekdays)
- Navbar: A user who is not a sitter can see the option "Become a sitter". It simply takes them to the edit profile page. A user who is a sitter instead sees "My jobs", which is a page we'll add later

**Comment by dproc96** [comment]
Signing off for tonight but here's where I left off on this:
- Created a page for Become A Sitter, it makes a PUT request to make the logged in user a sitter and then redirects them to an availability page (Included a circular progress in case the request is slow)
- Made Navbar display contingent on user type
- Added a page to Profile Settings for Availability that only shows if user is a Sitter
